#include "Theme.h"

#include <QApplication>

namespace Theme {

QString styleSheet()
{
    return QStringLiteral(
        "QMainWindow, QWidget {"
        "  background-color: %1;"
        "  color: %2;"
        "  border-color: %3;"
        "}"
        "QMenuBar {"
        "  background-color: %4;"
        "  color: %2;"
        "  border-bottom: 1px solid %3;"
        "}"
        "QMenuBar::item:selected {"
        "  background-color: %5;"
        "}"
        "QMenu {"
        "  background-color: %4;"
        "  color: %2;"
        "  border: 1px solid %3;"
        "}"
        "QMenu::item:selected {"
        "  background-color: %5;"
        "}"
        "QToolBar {"
        "  background-color: %4;"
        "  border-bottom: 1px solid %3;"
        "  spacing: 4px;"
        "  padding: 2px;"
        "}"
        "QStatusBar {"
        "  background-color: %6;"
        "  color: %7;"
        "  border-top: 1px solid %3;"
        "  font-size: 12px;"
        "}"
        "QLineEdit {"
        "  background-color: %1;"
        "  color: %2;"
        "  border: 1px solid %3;"
        "  padding: 4px 8px;"
        "  font-family: 'JetBrains Mono', 'Cascadia Mono', 'Noto Sans Mono', monospace;"
        "  font-size: 13px;"
        "  selection-background-color: %5;"
        "}"
        "QLineEdit:focus {"
        "  border-color: %8;"
        "}"
        "QTextBrowser {"
        "  background-color: %9;"
        "  color: %2;"
        "  border: none;"
        "  font-family: 'JetBrains Mono', 'Cascadia Mono', 'Noto Sans Mono', monospace;"
        "  font-size: 14px;"
        "  selection-background-color: %5;"
        "}"
        "QTreeWidget {"
        "  background-color: %10;"
        "  color: %2;"
        "  border: none;"
        "  outline: none;"
        "  font-size: 13px;"
        "}"
        "QTreeWidget::item {"
        "  padding: 3px 6px;"
        "  border: none;"
        "}"
        "QTreeWidget::item:selected {"
        "  background-color: %5;"
        "  color: %2;"
        "}"
        "QTreeWidget::item:hover {"
        "  background-color: %11;"
        "}"
        "QTabWidget::pane {"
        "  border: none;"
        "  background-color: %9;"
        "}"
        "QTabBar::tab {"
        "  background-color: %10;"
        "  color: %7;"
        "  padding: 6px 14px;"
        "  border: none;"
        "  border-right: 1px solid %3;"
        "  font-size: 12px;"
        "}"
        "QTabBar::tab:selected {"
        "  background-color: %9;"
        "  color: %2;"
        "  border-bottom: 2px solid %8;"
        "}"
        "QTabBar::tab:hover {"
        "  background-color: %11;"
        "}"
        "QScrollBar:vertical {"
        "  background-color: %10;"
        "  width: 10px;"
        "  border: none;"
        "}"
        "QScrollBar::handle:vertical {"
        "  background-color: %3;"
        "  min-height: 30px;"
        "  border-radius: 3px;"
        "}"
        "QScrollBar::handle:vertical:hover {"
        "  background-color: %8;"
        "}"
        "QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {"
        "  height: 0px;"
        "}"
        "QScrollBar:horizontal {"
        "  background-color: %10;"
        "  height: 10px;"
        "  border: none;"
        "}"
        "QScrollBar::handle:horizontal {"
        "  background-color: %3;"
        "  min-width: 30px;"
        "  border-radius: 3px;"
        "}"
        "QScrollBar::handle:horizontal:hover {"
        "  background-color: %8;"
        "}"
        "QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {"
        "  width: 0px;"
        "}"
        "QPushButton {"
        "  background-color: %11;"
        "  color: %2;"
        "  border: 1px solid %3;"
        "  padding: 4px 12px;"
        "  font-size: 12px;"
        "}"
        "QPushButton:hover {"
        "  background-color: %5;"
        "}"
        "QPushButton:pressed {"
        "  background-color: %8;"
        "}"
        "QComboBox {"
        "  background-color: %1;"
        "  color: %2;"
        "  border: 1px solid %3;"
        "  padding: 4px 8px;"
        "  font-size: 12px;"
        "}"
        "QComboBox::drop-down {"
        "  border: none;"
        "}"
        "QComboBox::down-arrow {"
        "  image: none;"
        "}"
        "QComboBox QAbstractItemView {"
        "  background-color: %4;"
        "  color: %2;"
        "  border: 1px solid %3;"
        "  selection-background-color: %5;"
        "}"
        "QPlainTextEdit {"
        "  background-color: %10;"
        "  color: %2;"
        "  border: 1px solid %3;"
        "  font-family: 'JetBrains Mono', 'Cascadia Mono', 'Noto Sans Mono', monospace;"
        "  font-size: 13px;"
        "  selection-background-color: %5;"
        "}"
        "QCheckBox {"
        "  color: %2;"
        "}"
        "QCheckBox::indicator {"
        "  border: 1px solid %3;"
        "  width: 14px;"
        "  height: 14px;"
        "}"
        "QCheckBox::indicator:checked {"
        "  background-color: %8;"
        "}"
        "QLabel {"
        "  color: %2;"
        "  border: none;"
        "}"
        "QSplitter::handle {"
        "  background-color: %3;"
        "}"
        "QSplitter::handle:horizontal {"
        "  width: 1px;"
        "}"
        "QSplitter::handle:vertical {"
        "  height: 1px;"
        "}"
        "QListWidget {"
        "  background-color: %10;"
        "  color: %2;"
        "  border: none;"
        "  font-size: 12px;"
        "  outline: none;"
        "}"
        "QListWidget::item:selected {"
        "  background-color: %5;"
        "}"
    )
        .arg(background.name())
        .arg(primaryText.name())
        .arg(borders.name())
        .arg(toolbar.name())
        .arg(selected.name())
        .arg(statusBar.name())
        .arg(secondaryText.name())
        .arg(accent().name())
        .arg(readingArea.name())
        .arg(sidebar.name())
        .arg(hover.name());
}

void apply()
{
    qApp->setStyleSheet(styleSheet());
}

} // namespace Theme
